spring:
  application:
    name: inkvite-back
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

resend:
  api-key: ${RESEND_API_KEY:}

app:
  base-url: ${APP_BASE_URL:}
  jwt:
    secret: ${APP_JWT_SECRET}
    access-token-expiry: 900
  email:
    from: ${APP_EMAIL_FROM:noreply@inkvite.me}
  storage:
    endpoint: ${APP_STORAGE_ENDPOINT:}
    bucket: ${APP_STORAGE_BUCKET:}
    access-key: ${APP_STORAGE_ACCESS_KEY:}
    secret-key: ${APP_STORAGE_SECRET_KEY:}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
